' Gambas module file

Public Sub anade(msg As String)
  'añade una linea al gridviews que muestra los mensajes

  Dim scad As String[]
  If msg <> "" Then
    'el mensaje debe de ser interpresatdo, por ejemplo el primer campo seria el color y el segundo el mensaje en si.
    scad = Split(msg, "|")
    If Val(scad[0]) = Null Then
      scad[0] = "0"
    Endif
    var.lineamensaje += 1
    If FMain.Gridmensajes.rows.count < var.lineamensaje Then
      FMain.Gridmensajes.rows.count = var.lineamensaje
    Endif
    ' [GB2:FCOL] FMain.Gridmensajes[var.lineamensaje - 1, 0].ForeColor = Val(scad[0])
    FMain.Gridmensajes[var.lineamensaje - 1, 0].Foreground = Val(scad[0])
    FMain.Gridmensajes[var.lineamensaje - 1, 0].text = scad[1]
    If var.lineamensaje > 13 Then
      FMain.Gridmensajes.ScrollY = var.lineamensaje * 20
    Endif
    FMain.Gridmensajes.Refresh
  Endif

End

Public Sub Titulos_Gridmensajes()

  With FMain.Gridmensajes
    .header = 3
    .rows.count = 0
    .rows.count = 25
    .columns.count = 2
    .Columns[0].title = "Mensajes"
    .Columns[0].width = 1592
    .font.name = "Sans"
    .font.size = 9
    .Foreground = 0
  End With

End
